const images = {
    'Asiacell': require('../../assets/circles/Asiacell.png'),
    'korek': require('../../assets/circles/korek.png'),
    'Zain': require('../../assets/circles/Zain.png'),
    'Pubg': require('../../assets/circles/Pubg.png'),
    'iTunes': require('../../assets/circles/iTunes.png'),
    'Xbox': require('../../assets/circles/Xbox.png'),
    'Google Play': require('../../assets/circles/GooglePlay.png'),
    'Iraqcell': require('../../assets/circles/Iraqcell.png'),
    'Tishknet': require('../../assets/circles/Tishknet.png'),
    'Shahid': require('../../assets/circles/Shahid.png'),
    'Nintendo': require('../../assets/circles/Nintendo.png'),
    'Amazon': require('../../assets/circles/amazon.png'),
    'Ebay': require('../../assets/circles/ebay.png'),
    'FreeFire': require('../../assets/circles/freefire.png'),
    'Skype': require('../../assets/circles/Skype.png'),
    'MineCraft': require('../../assets/circles/MineCraft.png'),
    'Netflix': require('../../assets/circles/Netflix.png'),
    'TrainNet': require('../../assets/circles/TrainNet.png'),
    'Newroz 4G': require('../../assets/circles/Newroz4G.png'),
    'FTTH': require('../../assets/circles/FTTH.png'),
    'FastLink': require('../../assets/circles/fastlink.png'),
    'FIFA': require('../../assets/circles/fifa.png'),
    'ADSL': require('../../assets/circles/ADSL.png'),
    'McAfee': require('../../assets/circles/McAfee.png'),
    'BLUTV': require('../../assets/circles/BLUTV.png'),
    'Bigo Live': require('../../assets/circles/Bigo.png'),
    'Conquerors': require('../../assets/circles/conquerors.png'),
    'Fortnite': require('../../assets/circles/fortnite.png'),
    'Likee': require('../../assets/circles/Likee.png'),
    'Careem': require('../../assets/circles/careem.png'),
    'Razer': require('../../assets/circles/Razer.png'),
    'PlayStation USA': require('../../assets/circles/playstation_am.png'),
    'Horzin Fi': require('../../assets/circles/HorzinFi.png'),
    'League of legends': require('../../assets/circles/Leagueoflegends.png'),
    'RuneScape': require('../../assets/circles/RuneScape.png'),
    'Blade and Soul': require('../../assets/circles/bladeandsoul.png'),
    'spotify': require('../../assets/circles/spotify.png'),
    'Mobile Legends': require('../../assets/circles/MobileLegends.png'),
    'Asiacell Data': require('../../assets/circles/AsiacellData.png'),
    'Mobile lords': require('../../assets/circles/Mobilelords.png'),
    'Steam USA': require('../../assets/circles/Steam_am.png'),
    'Steam Argentina': require('../../assets/circles/Steam_argentina.png'),
    'MasterCard': require('../../assets/circles/MasterCard.png'),
    'Roblex': require('../../assets/circles/Roblex.png'),
    'IQ online': require('../../assets/circles/IQonline.png'),
    'Zain Data': require('../../assets/circles/ZainData.png'),
    'yalla ludo': require('../../assets/circles/ludo.png'),
    'Bein Connect': require('../../assets/circles/ludo.png'),
    'PlayStation Emirates': require('../../assets/circles/playstation_emirates.png'),
}

export default images;